Kafka
eyakauleva/user-microservice pull request #18
Opened 2023-03-14 14:43 UTC by eyakauleva

close #17

2023-03-14 16:15 UTC, h1alexbel requested changes

2023-03-14 16:15 UTC, h1alexbel commented on docker-compose.yaml
> +services:
move to k8s

2023-03-14 16:15 UTC, h1alexbel commented on src/main/resources/application.yaml
> +    bootstrap-servers: localhost:9092
host is hardcoded

2023-03-15 10:52 UTC, eyakauleva commented on src/main/resources/application.yaml
> +    bootstrap-servers: localhost:9092
fix in 255168a

2023-03-15 10:53 UTC, eyakauleva commented on docker-compose.yaml
> +services:
I will implement k8s in the next PR

2023-03-15 11:46 UTC, h1alexbel approved these changes

2023-03-15 11:47 UTC, merged