k8s
eyakauleva/user-microservice pull request #20
Opened 2023-03-15 14:22 UTC by eyakauleva

close #19

2023-03-20 15:02 UTC, h1alexbel requested changes

2023-03-20 15:02 UTC, h1alexbel commented on src/infra/execute.sh
> +minikube service user-service
since you are using `minikube` here, it's better to name script `local.sh` or `minikube.sh`

2023-03-20 16:30 UTC, h1alexbel requested changes

2023-03-20 16:30 UTC, h1alexbel commented on src/infra/zookeeper-deployment.yaml
> +kind: Deployment
zookeeper should be a stateful set

2023-03-21 05:56 UTC, eyakauleva commented on src/infra/zookeeper-deployment.yaml
> +kind: Deployment
fixed 89b30ff

2023-03-21 08:25 UTC, h1alexbel approved these changes

2023-03-21 08:26 UTC, merged

2023-03-21 08:26 UTC, h1alexbel commented
@eyakauleva cheers