istio
eyakauleva/user-microservice pull request #31
Opened 2023-04-17 15:43 UTC by eyakauleva

2023-04-20 11:57 UTC, h1alexbel requested changes

2023-04-20 11:57 UTC, h1alexbel commented on src/infra/tickets-deployment.yaml
> +          image: eyakauleva/ticket-service
use versioning

https://semver.org/

2023-04-21 12:09 UTC, h1alexbel approved these changes

2023-04-21 14:27 UTC, eyakauleva commented on src/infra/tickets-deployment.yaml
> +          image: eyakauleva/ticket-service
fixed in 114690c & fa5cb2a

2023-04-21 16:10 UTC, h1alexbel approved these changes

2023-04-21 16:10 UTC, merged